### ISSUE TITLE
Setar linha digitavel customizavel

### ISSUE THREAD

**Issue by GabrielDevLoper** [braully/bopepo#14]
Opa amigo boa tarde, gostaria de saber se e possivel criar um metodo que aceite uma linha digitavel que ja possuo.

**Comment by braully** [comment]
Olá. Dei uma olhada no codigo dessa parte e você pode tentar criar um novo construtor para para a classe LinhaDigitavel passando a linha digitavel que você já possui. Se conseguir fazer algo legal me envie o pull request que libero na proxima versão.

**Comment by braully** [comment]
Você pode setar todos os campos do string e imagem e preencher o layout. Olhar o código do PdfDocMix, PdfReader e BoletoViewer.
