### ISSUE TITLE
Versão do compilador do JAR

### ISSUE THREAD

**Issue by ulissesc** [braully/bopepo#19]
Olá Braully,

estou migrando para a versão 1.0.1, no entanto estamos tendo o problema com o seguinte erro:

`org/jrimum/bopepo/BancosSuportados has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 (unable to load class [org.jrimum.bopepo.BancosSuportados])`

Nós utilizamos na execução o Java 8. Aparentemente só funciona com o Java 11 ou superior. Existe alguma possibilidade de compilar o jar para versões mais antigas do Java?

**Comment by braully** [comment]
Olá Ulisses. Esse fork foi feito com objetivo de atualizar a lib e suas dependencias. Principalmente Java 11. Acredito que seja possível você fazer um clone do projeto e tentar compilar para o Java 8 com pequenas modificações. Porém não tenho planos para compatibilidade para versões anteriores.
