### ISSUE TITLE
Santander 8 ou 9 digitos

### ISSUE THREAD

**Issue by robsonlira** [braully/bopepo#6]
OLá! Prezado eu tentei implementar 8 digitos da conta do Santander, baixei o projeto bopepo aqui do Github alterei a classe CLBancoSantander com private static final Integer FIELDS_LENGTH = 8 na linha 97 
e alterei também TestCLBancoSantander mais com certeza deve ser algo mais a ser feito poderia ajudar? eu não tenho tantos conhecimentos no java para desenrolar esta se puder ajudar ou indicar como eu postei la no grupo, e criei aqui o Issue porque vi que aqui vc também deve estar com apenas 6 digitos

**Comment by braully** [comment]
Conforme entendimento em discussão no grupo, essa opção não é aceita pelo banco. Somente 7 dígitos.
https://groups.google.com/g/jrimum-community/c/5lv7WiX1Mmo/m/Eue8ZSGlAwAJ?utm_medium=email&utm_source=footer
